<?php

namespace ContainerDKxz4PU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_DA4pGEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.DA4p_gE' shared service.
     *
     * @return \App\src\Repository\MovieRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\MovieController::index()": the $movieRepository argument is type-hinted with the non-existent class or interface: "App\\src\\Repository\\MovieRepository".');
    }
}
