<?php

namespace ContainerDKxz4PU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UQbWzIqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UQbWzIq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UQbWzIq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'movieRepository' => ['privates', '.errored.DA4p_gE', NULL, 'Cannot determine controller argument for "App\\Controller\\MovieController::index()": the $movieRepository argument is type-hinted with the non-existent class or interface: "App\\src\\Repository\\MovieRepository".'],
        ], [
            'movieRepository' => '?',
        ]);
    }
}
