<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC4IP3Ee\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC4IP3Ee/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC4IP3Ee.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC4IP3Ee\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC4IP3Ee\App_KernelDevDebugContainer([
    'container.build_hash' => 'C4IP3Ee',
    'container.build_id' => '8c69f215',
    'container.build_time' => 1710953927,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC4IP3Ee');
