<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI48sjxW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI48sjxW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI48sjxW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI48sjxW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI48sjxW\App_KernelDevDebugContainer([
    'container.build_hash' => 'I48sjxW',
    'container.build_id' => '281f0e74',
    'container.build_time' => 1710952153,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI48sjxW');
