<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMUy0uBA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMUy0uBA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMUy0uBA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMUy0uBA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMUy0uBA\App_KernelDevDebugContainer([
    'container.build_hash' => 'MUy0uBA',
    'container.build_id' => 'a7f2f0af',
    'container.build_time' => 1710974307,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMUy0uBA');
